export default [
  { value: "3D Engineering", label: "3D Engineering", group: "Engineering" },
  { value: "3D Modeling", label: "3D Modeling", group: "Design" },
  { value: "Ada", label: "Ada", group: "Engineering" },
  {
    value: "Adobe Creative Cloud",
    label: "Adobe Creative Cloud",
    group: "Design",
  },
  {
    value: "Adobe Experience Manager",
    label: "Adobe Experience Manager",
    group: "Design",
  },
  { value: "Agora", label: "Agora", group: "Engineering" },
  { value: "Algorithm Design", label: "Algorithm Design", group: "Data" },
  { value: "Amazon Athena", label: "Amazon Athena", group: "Data" },
  { value: "Amplitude", label: "Amplitude", group: "Data" },
  { value: "Android", label: "Android", group: "Engineering" },
  { value: "Angular", label: "Angular", group: "Engineering" },
  { value: "Angular.js", label: "Angular.js", group: "Engineering" },
  { value: "Ansible", label: "Ansible", group: "DevOps" },
  {
    value: "Apex (Salesforce)",
    label: "Apex (Salesforce)",
    group: "Engineering",
  },
  { value: "API Design", label: "API Design", group: "Engineering" },
  { value: "APNS", label: "APNS", group: "Engineering" },
  { value: "Apollo", label: "Apollo", group: "Engineering" },
  { value: "App Clip (iOS)", label: "App Clip (iOS)", group: "Engineering" },
  { value: "ArangoDB", label: "ArangoDB", group: "Data" },
  { value: "ARM", label: "ARM", group: "Engineering" },
  { value: "Artifactory", label: "Artifactory", group: "DevOps" },
  {
    value: "Artificial Intelligence (AI)",
    label: "Artificial Intelligence (AI)",
    group: "Data",
  },
  { value: "ASP.NET", label: "ASP.NET", group: "Engineering" },
  { value: "Assembly", label: "Assembly", group: "Engineering" },
  { value: "Async.io", label: "Async.io", group: "Engineering" },
  { value: "Aurelia", label: "Aurelia", group: "Engineering" },
  { value: "Authentication", label: "Authentication", group: "Engineering" },
  {
    value: "Automated Testing",
    label: "Automated Testing",
    group: "Engineering",
  },
  { value: "AWS Aurora", label: "AWS Aurora", group: "Cloud Technologies" },
  { value: "AWS BETA", label: "AWS BETA", group: "Cloud Technologies" },
  { value: "AWS CDK", label: "AWS CDK", group: "Cloud Technologies" },
  {
    value: "AWS CloudFormation",
    label: "AWS CloudFormation",
    group: "Cloud Technologies",
  },
  { value: "AWS Lambda", label: "AWS Lambda", group: "Cloud Technologies" },
  { value: "AWS Neptune", label: "AWS Neptune", group: "Cloud Technologies" },
  { value: "AWS RDS", label: "AWS RDS", group: "Cloud Technologies" },
  { value: "Azure", label: "Azure", group: "Cloud Technologies" },
  { value: "Babylon.js", label: "Babylon.js", group: "Engineering" },
  { value: "Backbone.js", label: "Backbone.js", group: "Engineering" },
  { value: "BigQuery", label: "BigQuery", group: "Data" },
  { value: "BLE (Bluetooth)", label: "BLE (Bluetooth)", group: "Engineering" },
  {
    value: "Blockchain / Crypto",
    label: "Blockchain / Crypto",
    group: "Engineering",
  },
  { value: "Bloomreach", label: "Bloomreach", group: "Engineering" },
  { value: "Bootstrap JS", label: "Bootstrap JS", group: "Engineering" },
  { value: "Boto3", label: "Boto3", group: "Cloud Technologies" },
  { value: "C", label: "C", group: "Engineering" },
  { value: "C#", label: "C#", group: "Engineering" },
  { value: "C++", label: "C++", group: "Engineering" },
  { value: "Capacitor", label: "Capacitor", group: "Engineering" },
  { value: "Cassandra", label: "Cassandra", group: "Data" },
  { value: "CI/CD", label: "CI/CD", group: "DevOps" },
  { value: "CircleCl", label: "CircleCl", group: "DevOps" },
  { value: "Clojure", label: "Clojure", group: "Engineering" },
  { value: "CMS", label: "CMS", group: "Engineering" },
  { value: "COBOL", label: "COBOL", group: "Engineering" },
  { value: "Coffeescript", label: "Coffeescript", group: "Engineering" },
  {
    value: "Combine Framework (Swift)",
    label: "Combine Framework (Swift)",
    group: "Engineering",
  },
  { value: "Computer Vision", label: "Computer Vision", group: "Data" },
  {
    value: "Concurrent programming",
    label: "Concurrent programming",
    group: "Engineering",
  },
  { value: "Contentful", label: "Contentful", group: "Engineering" },
  { value: "Contently", label: "Contently", group: "Other" },
  { value: "Cordova", label: "Cordova", group: "Engineering" },
  { value: "Cryptography", label: "Cryptography", group: "Engineering" },
  { value: "CSS", label: "CSS", group: "Design" },
  { value: "CUDA", label: "CUDA", group: "Engineering" },
  { value: "Cypress", label: "Cypress", group: "Engineering" },
  { value: "D3.js", label: "D3.js", group: "Data" },
  {
    value: "DAO (engineering)",
    label: "DAO (engineering)",
    group: "Engineering",
  },
  { value: "Dart", label: "Dart", group: "Engineering" },
  { value: "Data Architecture", label: "Data Architecture", group: "Data" },
  { value: "Data Management", label: "Data Management", group: "Data" },
  { value: "Data Modeling", label: "Data Modeling", group: "Data" },
  { value: "Data Pipelines", label: "Data Pipelines", group: "Data" },
  { value: "Data Taxonomy", label: "Data Taxonomy", group: "Data" },
  { value: "Data Visualization", label: "Data Visualization", group: "Data" },
  { value: "Databricks", label: "Databricks", group: "Data" },
  { value: "DataDog", label: "DataDog", group: "Data" },
  { value: "Dax", label: "Dax", group: "Data" },
  { value: "Dax Studio", label: "Dax Studio", group: "Data" },
  { value: "Deep learning", label: "Deep learning", group: "Data" },
  { value: "Delphi", label: "Delphi", group: "Engineering" },
  { value: "Design Sprint", label: "Design Sprint", group: "Design" },
  { value: "Design Systems", label: "Design Systems", group: "Design" },
  { value: "DevOps", label: "DevOps", group: "DevOps" },
  { value: "Directus", label: "Directus", group: "Engineering" },
  { value: "Discord.py", label: "Discord.py", group: "Engineering" },
  { value: "Django", label: "Django", group: "Engineering" },
  { value: "DMX Protocol", label: "DMX Protocol", group: "Engineering" },
  { value: "Docker", label: "Docker", group: "DevOps" },
  { value: "DynamoDB", label: "DynamoDB", group: "Data" },
  { value: "ECR", label: "ECR", group: "DevOps" },
  { value: "EditorX", label: "EditorX", group: "Design" },
  { value: "EKS", label: "EKS", group: "DevOps" },
  { value: "Elastic Search", label: "Elastic Search", group: "Data" },
  { value: "Electron", label: "Electron", group: "Engineering" },
  { value: "Elementor", label: "Elementor", group: "Design" },
  { value: "Elixir", label: "Elixir", group: "Engineering" },
  { value: "ELK Stack", label: "ELK Stack", group: "Data" },
  { value: "Elm", label: "Elm", group: "Engineering" },
  {
    value: "Email Deliverability",
    label: "Email Deliverability",
    group: "Marketing",
  },
  {
    value: "Embedded Software",
    label: "Embedded Software",
    group: "Engineering",
  },
  { value: "Ember.js", label: "Ember.js", group: "Engineering" },
  { value: "Erlang", label: "Erlang", group: "Engineering" },
  { value: "ES6+", label: "ES6+", group: "Engineering" },
  {
    value: "Ethereum (engineering)",
    label: "Ethereum (engineering)",
    group: "Engineering",
  },
  { value: "Ethers.js", label: "Ethers.js", group: "Engineering" },
  { value: "ETL", label: "ETL", group: "Data" },
  { value: "Expo", label: "Expo", group: "Engineering" },
  { value: "Express.js", label: "Express.js", group: "Engineering" },
  { value: "F#", label: "F#", group: "Engineering" },
  { value: "Fast API", label: "Fast API", group: "Engineering" },
  { value: "Fast.ai", label: "Fast.ai", group: "Data" },
  { value: "FFMPEG", label: "FFMPEG", group: "Engineering" },
  { value: "Firebase", label: "Firebase", group: "Engineering" },
  { value: "Flask", label: "Flask", group: "Engineering" },
  { value: "Flink", label: "Flink", group: "Data" },
  { value: "Flutter", label: "Flutter", group: "Engineering" },
  { value: "Frida", label: "Frida", group: "Engineering" },
  { value: "Fundraising", label: "Fundraising", group: "Business" },
  { value: "Game Testing", label: "Game Testing", group: "Engineering" },
  { value: "Gatsby.js", label: "Gatsby.js", group: "Engineering" },
  { value: "GitHub", label: "GitHub", group: "DevOps" },
  { value: "Go", label: "Go", group: "Engineering" },
  { value: "GoCD", label: "GoCD", group: "DevOps" },
  {
    value: "Google Cloud / GCP",
    label: "Google Cloud / GCP",
    group: "Cloud Technologies",
  },
  { value: "GPS", label: "GPS", group: "Engineering" },
  { value: "GPT / OpenAI", label: "GPT / OpenAI", group: "Data" },
  { value: "GPU", label: "GPU", group: "Engineering" },
  { value: "Grafana", label: "Grafana", group: "DevOps" },
  { value: "Graphic Rendering", label: "Graphic Rendering", group: "Design" },
  { value: "GraphQL", label: "GraphQL", group: "Engineering" },
  { value: "Groovy", label: "Groovy", group: "Engineering" },
  { value: "Hadoop", label: "Hadoop", group: "Data" },
  { value: "Hardware Design", label: "Hardware Design", group: "Engineering" },
  { value: "Haskell", label: "Haskell", group: "Engineering" },
  { value: "Hasura", label: "Hasura", group: "Data" },
  { value: "HCI", label: "HCI", group: "Design" },
  { value: "Heroku", label: "Heroku", group: "DevOps" },
  { value: "HiveQL", label: "HiveQL", group: "Data" },
  { value: "Hotwire", label: "Hotwire", group: "Engineering" },
  { value: "HTML", label: "HTML", group: "Design" },
  { value: "IBM Sterling", label: "IBM Sterling", group: "Business" },
  { value: "InDesign", label: "InDesign", group: "Design" },
  {
    value: "Instant app (Android)",
    label: "Instant app (Android)",
    group: "Engineering",
  },
  { value: "Ionic", label: "Ionic", group: "Engineering" },
  { value: "iOS", label: "iOS", group: "Engineering" },
  { value: "iOS App Clips", label: "iOS App Clips", group: "Engineering" },
  { value: "JamStack", label: "JamStack", group: "Engineering" },
  { value: "Java", label: "Java", group: "Engineering" },
  { value: "JavaScript", label: "JavaScript", group: "Engineering" },
  { value: "Jenkins", label: "Jenkins", group: "DevOps" },
  { value: "JEST", label: "JEST", group: "Engineering" },
  { value: "Jetpack Compose", label: "Jetpack Compose", group: "Engineering" },
  { value: "jQuery", label: "jQuery", group: "Engineering" },
  { value: "Kafka", label: "Kafka", group: "Data" },
  { value: "Keras", label: "Keras", group: "Data" },
  { value: "Kinesis", label: "Kinesis", group: "Data" },
  { value: "Kotlin", label: "Kotlin", group: "Engineering" },
  { value: "Kubernetes", label: "Kubernetes", group: "DevOps" },
  { value: "LangChain", label: "LangChain", group: "Data" },
  { value: "Laravel", label: "Laravel", group: "Engineering" },
  { value: "LaunchDarkly", label: "LaunchDarkly", group: "DevOps" },
  { value: "LESS", label: "LESS", group: "Design" },
  { value: "Linux", label: "Linux", group: "Engineering" },
  { value: "Llama / Llama 2", label: "Llama / Llama 2", group: "Data" },
  { value: "Load Testing", label: "Load Testing", group: "Engineering" },
  { value: "Loader.io", label: "Loader.io", group: "DevOps" },
  { value: "Lua", label: "Lua", group: "Engineering" },
  { value: "Machine Learning", label: "Machine Learning", group: "Data" },
  { value: "Matlab", label: "Matlab", group: "Engineering" },
  { value: "Mediasoup", label: "Mediasoup", group: "Engineering" },
  {
    value: "Mergers & Acquisitions",
    label: "Mergers & Acquisitions",
    group: "Business",
  },
  { value: "Messagequeue", label: "Messagequeue", group: "Engineering" },
  { value: "Meteor.js", label: "Meteor.js", group: "Engineering" },
  { value: "Microservices", label: "Microservices", group: "Engineering" },
  { value: "Miro", label: "Miro", group: "Design" },
  { value: "Mobile Game Design", label: "Mobile Game Design", group: "Design" },
  { value: "MobX", label: "MobX", group: "Engineering" },
  { value: "MongoDB", label: "MongoDB", group: "Data" },
  { value: "Motion Design", label: "Motion Design", group: "Design" },
  { value: "Multi-Threading", label: "Multi-Threading", group: "Engineering" },
  { value: "MySQL", label: "MySQL", group: "Data" },
  { value: "Nest.js", label: "Nest.js", group: "Engineering" },
  { value: ".NET", label: ".NET", group: "Engineering" },
  { value: "Neural Networks", label: "Neural Networks", group: "Data" },
  { value: "NewRelic", label: "NewRelic", group: "DevOps" },
  { value: "Next.js", label: "Next.js", group: "Engineering" },
  { value: "NLP", label: "NLP", group: "Data" },
  { value: "Node.js", label: "Node.js", group: "Engineering" },
  { value: "Numpy", label: "Numpy", group: "Data" },
  { value: "Nuxt", label: "Nuxt", group: "Engineering" },
  { value: "Objective-C", label: "Objective-C", group: "Engineering" },
  { value: "Ocaml", label: "Ocaml", group: "Engineering" },
  { value: "Oracle Apex", label: "Oracle Apex", group: "Engineering" },
  { value: "Pascal", label: "Pascal", group: "Engineering" },
  { value: "Passport.js", label: "Passport.js", group: "Engineering" },
  {
    value: "Penetration Testing",
    label: "Penetration Testing",
    group: "Security",
  },
  { value: "Perl", label: "Perl", group: "Engineering" },
  { value: "Phoenix", label: "Phoenix", group: "Engineering" },
  { value: "Photoshop", label: "Photoshop", group: "Design" },
  { value: "PHP", label: "PHP", group: "Engineering" },
  {
    value: "P&L Responsibility",
    label: "P&L Responsibility",
    group: "Business",
  },
  { value: "Playwright", label: "Playwright", group: "Engineering" },
  { value: "Polygon", label: "Polygon", group: "Engineering" },
  { value: "PostCSS", label: "PostCSS", group: "Design" },
  { value: "PostgreSQL", label: "PostgreSQL", group: "Data" },
  { value: "Preact", label: "Preact", group: "Engineering" },
  { value: "Figma", label: "Figma", group: "Design" },
  {
    value: "Presentation Design",
    label: "Presentation Design",
    group: "Design",
  },
  { value: "Product Design", label: "Product Design", group: "Design" },
  {
    value: "Program Development Life Cycle (PDLC)",
    label: "Program Development Life Cycle (PDLC)",
    group: "Engineering",
  },
  { value: "Prometheus", label: "Prometheus", group: "DevOps" },
  { value: "Prototyping", label: "Prototyping", group: "Design" },
  { value: "Public Cloud", label: "Public Cloud", group: "Cloud Technologies" },
  { value: "PySpark", label: "PySpark", group: "Data" },
  { value: "PySQL", label: "PySQL", group: "Data" },
  { value: "Python", label: "Python", group: "Engineering" },
  { value: "PyTorch", label: "PyTorch", group: "Data" },
  {
    value: "QA (Quality Assurance)",
    label: "QA (Quality Assurance)",
    group: "Engineering",
  },
  { value: "R (language)", label: "R (language)", group: "Data" },
  { value: "RabbitMQ", label: "RabbitMQ", group: "Engineering" },
  { value: "React", label: "React", group: "Engineering" },
  { value: "React Flow", label: "React Flow", group: "Engineering" },
  { value: "React Native", label: "React Native", group: "Engineering" },
  { value: "RealmDB", label: "RealmDB", group: "Data" },
  { value: "Redis", label: "Redis", group: "Data" },
  { value: "Redshift", label: "Redshift", group: "Data" },
  { value: "Redux", label: "Redux", group: "Engineering" },
  { value: "REST API", label: "REST API", group: "Engineering" },
  { value: "RISC-V", label: "RISC-V", group: "Engineering" },
  { value: "Robotics", label: "Robotics", group: "Engineering" },
  { value: "Rollbar", label: "Rollbar", group: "DevOps" },
  { value: "Ruby", label: "Ruby", group: "Engineering" },
  { value: "Ruby on Rails", label: "Ruby on Rails", group: "Engineering" },
  { value: "Rudderstack", label: "Rudderstack", group: "Data" },
  { value: "Rust", label: "Rust", group: "Engineering" },
  { value: "Rx", label: "Rx", group: "Engineering" },
  { value: "RxJava", label: "RxJava", group: "Engineering" },
  { value: "Sails.js", label: "Sails.js", group: "Engineering" },
  { value: "SASS", label: "SASS", group: "Design" },
  { value: "Scala", label: "Scala", group: "Engineering" },
  { value: "scikit-learn", label: "scikit-learn", group: "Data" },
  { value: "SDLC", label: "SDLC", group: "Engineering" },
  {
    value: "Security (Engineering)",
    label: "Security (Engineering)",
    group: "Security",
  },
  { value: "Segment", label: "Segment", group: "Data" },
  { value: "Selenium", label: "Selenium", group: "Engineering" },
  { value: "Sentry", label: "Sentry", group: "DevOps" },
  { value: "Serverless", label: "Serverless", group: "Engineering" },
  { value: "ServiceNow", label: "ServiceNow", group: "Business" },
  { value: "Shopify", label: "Shopify", group: "Engineering" },
  { value: "Sketch", label: "Sketch", group: "Design" },
  { value: "Smart Contracts", label: "Smart Contracts", group: "Engineering" },
  {
    value: "Social Media Strategy",
    label: "Social Media Strategy",
    group: "Marketing",
  },
  { value: "Sockets", label: "Sockets", group: "Engineering" },
  { value: "Solidity", label: "Solidity", group: "Engineering" },
  { value: "Solid.js", label: "Solid.js", group: "Engineering" },
  {
    value: "Sound Processing",
    label: "Sound Processing",
    group: "Engineering",
  },
  { value: "Spark", label: "Spark", group: "Data" },
  {
    value: "Speech Deep Learning",
    label: "Speech Deep Learning",
    group: "Data",
  },
  { value: "Speech Recognition", label: "Speech Recognition", group: "Data" },
  { value: "Splunk", label: "Splunk", group: "Data" },
  { value: "Spring", label: "Spring", group: "Engineering" },
  { value: "Spring Boot", label: "Spring Boot", group: "Engineering" },
  { value: "SQL", label: "SQL", group: "Data" },
  {
    value: "Statistical functions",
    label: "Statistical functions",
    group: "Data",
  },
  { value: "Storybook", label: "Storybook", group: "Engineering" },
  { value: "Strapi", label: "Strapi", group: "Engineering" },
  { value: "Svelte", label: "Svelte", group: "Engineering" },
  { value: "Swift", label: "Swift", group: "Engineering" },
  { value: "SwiftUI", label: "SwiftUI", group: "Engineering" },
  {
    value: "Systems Architecture",
    label: "Systems Architecture",
    group: "Engineering",
  },
  { value: "Tailwind CSS", label: "Tailwind CSS", group: "Design" },
  {
    value: "Technical Writing and Documentation",
    label: "Technical Writing and Documentation",
    group: "Other",
  },
  { value: "Tensorflow", label: "Tensorflow", group: "Data" },
  { value: "Terraform", label: "Terraform", group: "DevOps" },
  { value: "Text-to-Speech", label: "Text-to-Speech", group: "Data" },
  { value: "Tornado", label: "Tornado", group: "Engineering" },
  { value: "Transactional UX", label: "Transactional UX", group: "Design" },
  { value: "Trigger Testing", label: "Trigger Testing", group: "Engineering" },
  { value: "Type-Orm", label: "Type-Orm", group: "Engineering" },
  { value: "TypeScript", label: "TypeScript", group: "Engineering" },
  { value: "Unity", label: "Unity", group: "Engineering" },
  { value: "Unreal Engine", label: "Unreal Engine", group: "Engineering" },
  { value: "User Research", label: "User Research", group: "Design" },
  { value: "UX Design", label: "UX Design", group: "Design" },
  { value: "UX/UI", label: "UX/UI", group: "Design" },
  { value: "VBA", label: "VBA", group: "Engineering" },
  { value: "Visual Basic", label: "Visual Basic", group: "Engineering" },
  { value: "Visual design", label: "Visual design", group: "Design" },
  { value: "Vue.js", label: "Vue.js", group: "Engineering" },
  { value: "Wearable Design", label: "Wearable Design", group: "Design" },
  { value: "Web3", label: "Web3", group: "Engineering" },
  { value: "WebFlow", label: "WebFlow", group: "Design" },
  { value: "WebGL", label: "WebGL", group: "Engineering" },
  { value: "Webhooks", label: "Webhooks", group: "Engineering" },
  { value: "Webpack", label: "Webpack", group: "Engineering" },
  { value: "WebRTC", label: "WebRTC", group: "Engineering" },
  { value: "Wireframing", label: "Wireframing", group: "Design" },
  { value: "WordPress", label: "WordPress", group: "Engineering" },
  { value: "x86", label: "x86", group: "Engineering" },
  { value: "Xamarin", label: "Xamarin", group: "Engineering" },
  { value: "Zeet.co", label: "Zeet.co", group: "Engineering" },
  { value: "ZeroMQ", label: "ZeroMQ", group: "Engineering" },
  { value: "Zod", label: "Zod", group: "Engineering" },
  {
    value: "Strategic Foresight",
    label: "Strategic Foresight",
    group: "Business",
  },
  {
    value: "Regulatory Compliance Strategy",
    label: "Regulatory Compliance Strategy",
    group: "Business",
  },
  {
    value: "Crisis Strategy & Management",
    label: "Crisis Strategy & Management",
    group: "Business",
  },
  {
    value: "Stakeholder Engagement",
    label: "Stakeholder Engagement",
    group: "Business",
  },
  {
    value: "Global Business Management",
    label: "Global Business Management",
    group: "Business",
  },
  {
    value: "Cross-functional Team Leadership",
    label: "Cross-functional Team Leadership",
    group: "Management",
  },
  {
    value: "Mergers and Acquisitions",
    label: "Mergers and Acquisitions",
    group: "Business",
  },
  {
    value: "Data-Driven Decision Making",
    label: "Data-Driven Decision Making",
    group: "Data",
  },
  {
    value: "Ethical Leadership",
    label: "Ethical Leadership",
    group: "Management",
  },
  {
    value: "Strategic Business Planning",
    label: "Strategic Business Planning",
    group: "Business",
  },
  { value: "Agile Leadership", label: "Agile Leadership", group: "Management" },
  {
    value: "Digital Transformation Strategy",
    label: "Digital Transformation Strategy",
    group: "Business",
  },
  { value: "Financial Acumen", label: "Financial Acumen", group: "Business" },
  {
    value: "Change Management",
    label: "Change Management",
    group: "Management",
  },
  {
    value: "AI & Automation Strategy",
    label: "AI & Automation Strategy",
    group: "Technology",
  },
  {
    value: "Information Architecture",
    label: "Information Architecture",
    group: "Technology",
  },
  { value: "UX Testing", label: "UX Testing", group: "Design" },
  {
    value: "Virtual Reality (VR) Design",
    label: "Virtual Reality (VR) Design",
    group: "Design",
  },
  {
    value: "Influencer Marketing Strategy",
    label: "Influencer Marketing Strategy",
    group: "Marketing",
  },
  {
    value: "User Journey Mapping",
    label: "User Journey Mapping",
    group: "Design",
  },
  {
    value: "User Onboarding Design",
    label: "User Onboarding Design",
    group: "Design",
  },
  { value: "UX Writing", label: "UX Writing", group: "Design" },
  {
    value: "Iterative Prototyping",
    label: "Iterative Prototyping",
    group: "Design",
  },
  {
    value: "Product Roadmapping",
    label: "Product Roadmapping",
    group: "Business",
  },
  {
    value: "Augmented Reality (AR) Design",
    label: "Augmented Reality (AR) Design",
    group: "Design",
  },
  { value: "DeFi Governance", label: "DeFi Governance", group: "Finance" },
  {
    value: "Smart Contract Auditing",
    label: "Smart Contract Auditing",
    group: "Technology",
  },
  { value: "Framer", label: "Framer", group: "Design" },
  { value: "NFT Marketing", label: "NFT Marketing", group: "Marketing" },
  { value: "DAO Governance", label: "DAO Governance", group: "Finance" },
  {
    value: "Hybrid-remote Team Management",
    label: "Hybrid-remote Team Management",
    group: "Management",
  },
  {
    value: "Verifiable Credentials",
    label: "Verifiable Credentials",
    group: "Technology",
  },
  {
    value: "Quantum Computing",
    label: "Quantum Computing",
    group: "Technology",
  },
  {
    value: "Surveillance AI Ethics",
    label: "Surveillance AI Ethics",
    group: "Ethics",
  },
  {
    value: "Proactive AI Ethics",
    label: "Proactive AI Ethics",
    group: "Ethics",
  },
  {
    value: "Conversational Design",
    label: "Conversational Design",
    group: "Design",
  },
  { value: "AI Bias Detection", label: "AI Bias Detection", group: "Data" },
  { value: "Cybersecurity", label: "Cybersecurity", group: "Technology" },
  {
    value: "Interoperable Blockchains",
    label: "Interoperable Blockchains",
    group: "Technology",
  },
  { value: "DAO Architecture", label: "DAO Architecture", group: "Technology" },
  { value: "AI Ethics", label: "AI Ethics", group: "Ethics" },
  { value: "Mechatronics", label: "Mechatronics", group: "Engineering" },
  {
    value: "Metaverse Product Design",
    label: "Metaverse Product Design",
    group: "Design",
  },
  { value: "Web3 UX Design", label: "Web3 UX Design", group: "Design" },
  {
    value: "Scrum Methodology",
    label: "Scrum Methodology",
    group: "Management",
  },
  { value: "Kanban", label: "Kanban", group: "Management" },
  {
    value: "Agile Project Management",
    label: "Agile Project Management",
    group: "Management",
  },
  { value: "Agile Coaching", label: "Agile Coaching", group: "Management" },
  {
    value: "User Story Creation",
    label: "User Story Creation",
    group: "Design",
  },
  { value: "Jira", label: "Jira", group: "Technology" },
  {
    value: "Waterfall Project Management",
    label: "Waterfall Project Management",
    group: "Management",
  },
  {
    value: "Documentation Writing",
    label: "Documentation Writing",
    group: "Other",
  },
  {
    value: "Documentation Writing",
    label: "Documentation Writing",
    group: "Other",
  },
  { value: "Design Thinking", label: "Design Thinking", group: "Design" },
  { value: "Service Design", label: "Service Design", group: "Design" },
  { value: "Product Strategy", label: "Product Strategy", group: "Business" },
]
