export default [
  { value: "3D Engineering", label: "3D Engineering" },
  { value: "3D Modeling", label: "3D Modeling" },
  { value: "Ada", label: "Ada" },
  { value: "Adobe Creative Cloud", label: "Adobe Creative Cloud" },
  { value: "Adobe Experience Manager", label: "Adobe Experience Manager" },
  { value: "Agora", label: "Agora" },
  { value: "Algorithm Design", label: "Algorithm Design" },
  { value: "Amazon Athena", label: "Amazon Athena" },
  { value: "Amplitude", label: "Amplitude" },
  { value: "Android", label: "Android" },
  { value: "Angular", label: "Angular" },
  { value: "Angular.js", label: "Angular.js" },
  { value: "Ansible", label: "Ansible" },
  { value: "Apex (Salesforce)", label: "Apex (Salesforce)" },
  { value: "API Design", label: "API Design" },
  { value: "APNS", label: "APNS" },
  { value: "Apollo", label: "Apollo" },
  { value: "App Clip (iOS)", label: "App Clip (iOS)" },
  { value: "ArangoDB", label: "ArangoDB" },
  { value: "ARM", label: "ARM" },
  { value: "Artifactory", label: "Artifactory" },
  {
    value: "Artificial Intelligence (AI)",
    label: "Artificial Intelligence (AI)",
  },
  { value: "ASP.NET", label: "ASP.NET" },
  { value: "Assembly", label: "Assembly" },
  { value: "Async.io", label: "Async.io" },
  { value: "Aurelia", label: "Aurelia" },
  { value: "Authentication", label: "Authentication" },
  { value: "Automated Testing", label: "Automated Testing" },
  { value: "AWS Aurora", label: "AWS Aurora" },
  { value: "AWS BETA", label: "AWS BETA" },
  { value: "AWS CDK", label: "AWS CDK" },
  { value: "AWS CloudFormation", label: "AWS CloudFormation" },
  { value: "AWS Lambda", label: "AWS Lambda" },
  { value: "AWS Neptune", label: "AWS Neptune" },
  { value: "AWS RDS", label: "AWS RDS" },
  { value: "Azure", label: "Azure" },
  { value: "Babylon.js", label: "Babylon.js" },
  { value: "Backbone.js", label: "Backbone.js" },
  { value: "BigQuery", label: "BigQuery" },
  { value: "BLE (Bluetooth)", label: "BLE (Bluetooth)" },
  { value: "Blockchain / Crypto", label: "Blockchain / Crypto" },
  { value: "Bloomreach", label: "Bloomreach" },
  { value: "Bootstrap JS", label: "Bootstrap JS" },
  { value: "Boto3", label: "Boto3" },
  { value: "C", label: "C" },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  { value: "Capacitor", label: "Capacitor" },
  { value: "Cassandra", label: "Cassandra" },
  { value: "CI/CD", label: "CI/CD" },
  { value: "CircleCl", label: "CircleCl" },
  { value: "Clojure", label: "Clojure" },
  { value: "CMS", label: "CMS" },
  { value: "COBOL", label: "COBOL" },
  { value: "Coffeescript", label: "Coffeescript" },
  { value: "Combine Framework (Swift)", label: "Combine Framework (Swift)" },
  { value: "Computer Vision", label: "Computer Vision" },
  { value: "Concurrent programming", label: "Concurrent programming" },
  { value: "Contentful", label: "Contentful" },
  { value: "Contently", label: "Contently" },
  { value: "Cordova", label: "Cordova" },
  { value: "Cryptography", label: "Cryptography" },
  { value: "CSS", label: "CSS" },
  { value: "CUDA", label: "CUDA" },
  { value: "Cypress", label: "Cypress" },
  { value: "D3.js", label: "D3.js" },
  { value: "DAO (engineering)", label: "DAO (engineering)" },
  { value: "Dart", label: "Dart" },
  { value: "Data Architecture", label: "Data Architecture" },
  { value: "Data Management", label: "Data Management" },
  { value: "Data Modeling", label: "Data Modeling" },
  { value: "Data Pipelines", label: "Data Pipelines" },
  { value: "Data Taxonomy", label: "Data Taxonomy" },
  { value: "Data Visualization", label: "Data Visualization" },
  { value: "Databricks", label: "Databricks" },
  { value: "DataDog", label: "DataDog" },
  { value: "Dax", label: "Dax" },
  { value: "Dax Studio", label: "Dax Studio" },
  { value: "Deep learning", label: "Deep learning" },
  { value: "Delphi", label: "Delphi" },
  { value: "Design Sprint", label: "Design Sprint" },
  { value: "Design Systems", label: "Design Systems" },
  { value: "DevOps", label: "DevOps" },
  { value: "Directus", label: "Directus" },
  { value: "Discord.py", label: "Discord.py" },
  { value: "Django", label: "Django" },
  { value: "DMX Protocol", label: "DMX Protocol" },
  { value: "Docker", label: "Docker" },
  { value: "DynamoDB", label: "DynamoDB" },
  { value: "ECR", label: "ECR" },
  { value: "EditorX", label: "EditorX" },
  { value: "EKS", label: "EKS" },
  { value: "Elastic Search", label: "Elastic Search" },
  { value: "Electron", label: "Electron" },
  { value: "Elementor", label: "Elementor" },
  { value: "Elixir", label: "Elixir" },
  { value: "ELK Stack", label: "ELK Stack" },
  { value: "Elm", label: "Elm" },
  { value: "Email Deliverability", label: "Email Deliverability" },
  { value: "Embedded Software", label: "Embedded Software" },
  { value: "Ember.js", label: "Ember.js" },
  { value: "Erlang", label: "Erlang" },
  { value: "ES6+", label: "ES6+" },
  { value: "Ethereum (engineering)", label: "Ethereum (engineering)" },
  { value: "Ethers.js", label: "Ethers.js" },
  { value: "ETL", label: "ETL" },
  { value: "Expo", label: "Expo" },
  { value: "Express.js", label: "Express.js" },
  { value: "F#", label: "F#" },
  { value: "Fast API", label: "Fast API" },
  { value: "Fast.ai", label: "Fast.ai" },
  { value: "FFMPEG", label: "FFMPEG" },
  { value: "Firebase", label: "Firebase" },
  { value: "Flask", label: "Flask" },
  { value: "Flink", label: "Flink" },
  { value: "Flutter", label: "Flutter" },
  { value: "Frida", label: "Frida" },
  { value: "Fundraising", label: "Fundraising" },
  { value: "Game Testing", label: "Game Testing" },
  { value: "Gatsby.js", label: "Gatsby.js" },
  { value: "GitHub", label: "GitHub" },
  { value: "Go", label: "Go" },
  { value: "GoCD", label: "GoCD" },
  { value: "Google Cloud / GCP", label: "Google Cloud / GCP" },
  { value: "GPS", label: "GPS" },
  { value: "GPT / OpenAI", label: "GPT / OpenAI" },
  { value: "GPU", label: "GPU" },
  { value: "Grafana", label: "Grafana" },
  { value: "Graphic Rendering", label: "Graphic Rendering" },
  { value: "GraphQL", label: "GraphQL" },
  { value: "Groovy", label: "Groovy" },
  { value: "Hadoop", label: "Hadoop" },
  { value: "Hardware Design", label: "Hardware Design" },
  { value: "Haskell", label: "Haskell" },
  { value: "Hasura", label: "Hasura" },
  { value: "HCI", label: "HCI" },
  { value: "Heroku", label: "Heroku" },
  { value: "HiveQL", label: "HiveQL" },
  { value: "Hotwire", label: "Hotwire" },
  { value: "HTML", label: "HTML" },
  { value: "IBM Sterling", label: "IBM Sterling" },
  { value: "InDesign", label: "InDesign" },
  { value: "Instant app (Android)", label: "Instant app (Android)" },
  { value: "Ionic", label: "Ionic" },
  { value: "iOS", label: "iOS" },
  { value: "iOS App Clips", label: "iOS App Clips" },
  { value: "JamStack", label: "JamStack" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "JEST", label: "JEST" },
  { value: "Jetpack Compose", label: "Jetpack Compose" },
  { value: "jQuery", label: "jQuery" },
  { value: "Kafka", label: "Kafka" },
  { value: "Keras", label: "Keras" },
  { value: "Kinesis", label: "Kinesis" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "LangChain", label: "LangChain" },
  { value: "Laravel", label: "Laravel" },
  { value: "LaunchDarkly", label: "LaunchDarkly" },
  { value: "LESS", label: "LESS" },
  { value: "Linux", label: "Linux" },
  { value: "Llama / Llama 2", label: "Llama / Llama 2" },
  { value: "Load Testing", label: "Load Testing" },
  { value: "Loader.io", label: "Loader.io" },
  { value: "Lua", label: "Lua" },
  { value: "Machine Learning", label: "Machine Learning" },
  { value: "Matlab", label: "Matlab" },
  { value: "Mediasoup", label: "Mediasoup" },
  { value: "Mergers & Acquisitions", label: "Mergers & Acquisitions" },
  { value: "Messagequeue", label: "Messagequeue" },
  { value: "Meteor.js", label: "Meteor.js" },
  { value: "Microservices", label: "Microservices" },
  { value: "Miro", label: "Miro" },
  { value: "Mobile Game Design", label: "Mobile Game Design" },
  { value: "MobX", label: "MobX" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "Motion Design", label: "Motion Design" },
  { value: "Multi-Threading", label: "Multi-Threading" },
  { value: "MySQL", label: "MySQL" },
  { value: "Nest.js", label: "Nest.js" },
  { value: ".NET", label: ".NET" },
  { value: "Neural Networks", label: "Neural Networks" },
  { value: "NewRelic", label: "NewRelic" },
  { value: "Next.js", label: "Next.js" },
  { value: "NLP", label: "NLP" },
  { value: "Node.js", label: "Node.js" },
  { value: "Numpy", label: "Numpy" },
  { value: "Nuxt", label: "Nuxt" },
  { value: "Objective-C", label: "Objective-C" },
  { value: "Ocaml", label: "Ocaml" },
  { value: "Oracle Apex", label: "Oracle Apex" },
  { value: "Pascal", label: "Pascal" },
  { value: "Passport.js", label: "Passport.js" },
  { value: "Penetration Testing", label: "Penetration Testing" },
  { value: "Perl", label: "Perl" },
  { value: "Phoenix", label: "Phoenix" },
  { value: "Photoshop", label: "Photoshop" },
  { value: "PHP", label: "PHP" },
  { value: "P&L Responsibility", label: "P&L Responsibility" },
  { value: "Playwright", label: "Playwright" },
  { value: "Polygon", label: "Polygon" },
  { value: "PostCSS", label: "PostCSS" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Preact", label: "Preact" },
  { value: "Figma", label: "Figma" },
  { value: "Presentation Design", label: "Presentation Design" },
  { value: "Product Design", label: "Product Design" },
  {
    value: "Program Development Life Cycle (PDLC)",
    label: "Program Development Life Cycle (PDLC)",
  },
  { value: "Prometheus", label: "Prometheus" },
  { value: "Prototyping", label: "Prototyping" },
  { value: "Public Cloud", label: "Public Cloud" },
  { value: "PySpark", label: "PySpark" },
  { value: "PySQL", label: "PySQL" },
  { value: "Python", label: "Python" },
  { value: "PyTorch", label: "PyTorch" },
  { value: "QA (Quality Assurance)", label: "QA (Quality Assurance)" },
  { value: "R (language)", label: "R (language)" },
  { value: "RabbitMQ", label: "RabbitMQ" },
  { value: "React", label: "React" },
  { value: "React Flow", label: "React Flow" },
  { value: "React Native", label: "React Native" },
  { value: "RealmDB", label: "RealmDB" },
  { value: "Redis", label: "Redis" },
  { value: "Redshift", label: "Redshift" },
  { value: "Redux", label: "Redux" },
  { value: "REST API", label: "REST API" },
  { value: "RISC-V", label: "RISC-V" },
  { value: "Robotics", label: "Robotics" },
  { value: "Rollbar", label: "Rollbar" },
  { value: "Ruby", label: "Ruby" },
  { value: "Ruby on Rails", label: "Ruby on Rails" },
  { value: "Rudderstack", label: "Rudderstack" },
  { value: "Rust", label: "Rust" },
  { value: "Rx", label: "Rx" },
  { value: "RxJava", label: "RxJava" },
  { value: "Sails.js", label: "Sails.js" },
  { value: "SASS", label: "SASS" },
  { value: "Scala", label: "Scala" },
  { value: "scikit-learn", label: "scikit-learn" },
  { value: "SDLC", label: "SDLC" },
  { value: "Security (Engineering)", label: "Security (Engineering)" },
  { value: "Segment", label: "Segment" },
  { value: "Selenium", label: "Selenium" },
  { value: "Sentry", label: "Sentry" },
  { value: "Serverless", label: "Serverless" },
  { value: "ServiceNow", label: "ServiceNow" },
  { value: "Shopify", label: "Shopify" },
  { value: "Sketch", label: "Sketch" },
  { value: "Smart Contracts", label: "Smart Contracts" },
  { value: "Social Media Strategy", label: "Social Media Strategy" },
  { value: "Sockets", label: "Sockets" },
  { value: "Solidity", label: "Solidity" },
  { value: "Solid.js", label: "Solid.js" },
  { value: "Sound Processing", label: "Sound Processing" },
  { value: "Spark", label: "Spark" },
  { value: "Speech Deep Learning", label: "Speech Deep Learning" },
  { value: "Speech Recognition", label: "Speech Recognition" },
  { value: "Splunk", label: "Splunk" },
  { value: "Spring", label: "Spring" },
  { value: "Spring Boot", label: "Spring Boot" },
  { value: "SQL", label: "SQL" },
  { value: "Statistical functions", label: "Statistical functions" },
  { value: "Storybook", label: "Storybook" },
  { value: "Strapi", label: "Strapi" },
  { value: "Svelte", label: "Svelte" },
  { value: "Swift", label: "Swift" },
  { value: "SwiftUI", label: "SwiftUI" },
  { value: "Systems Architecture", label: "Systems Architecture" },
  { value: "Tailwind CSS", label: "Tailwind CSS" },
  {
    value: "Technical Writing and Documentation",
    label: "Technical Writing and Documentation",
  },
  { value: "Tensorflow", label: "Tensorflow" },
  { value: "Terraform", label: "Terraform" },
  { value: "Text-to-Speech", label: "Text-to-Speech" },
  { value: "Tornado", label: "Tornado" },
  { value: "Transactional UX", label: "Transactional UX" },
  { value: "Trigger Testing", label: "Trigger Testing" },
  { value: "Type-Orm", label: "Type-Orm" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "Unity", label: "Unity" },
  { value: "Unreal Engine", label: "Unreal Engine" },
  { value: "User Research", label: "User Research" },
  { value: "UX Design", label: "UX Design" },
  { value: "UX/UI", label: "UX/UI" },
  { value: "VBA", label: "VBA" },
  { value: "Visual Basic", label: "Visual Basic" },
  { value: "Visual design", label: "Visual design" },
  { value: "Vue.js", label: "Vue.js" },
  { value: "Wearable Design", label: "Wearable Design" },
  { value: "Web3", label: "Web3" },
  { value: "WebFlow", label: "WebFlow" },
  { value: "WebGL", label: "WebGL" },
  { value: "Webhooks", label: "Webhooks" },
  { value: "Webpack", label: "Webpack" },
  { value: "WebRTC", label: "WebRTC" },
  { value: "Wireframing", label: "Wireframing" },
  { value: "WordPress", label: "WordPress" },
  { value: "x86", label: "x86" },
  { value: "Xamarin", label: "Xamarin" },
  { value: "Zeet.co", label: "Zeet.co" },
  { value: "ZeroMQ", label: "ZeroMQ" },
  { value: "Zod", label: "Zod" },
  { value: "Strategic Foresight", label: "Strategic Foresight" },
  {
    value: "Regulatory Compliance Strategy",
    label: "Regulatory Compliance Strategy",
  },
  {
    value: "Crisis Strategy & Management",
    label: "Crisis Strategy & Management",
  },
  { value: "Stakeholder Engagement", label: "Stakeholder Engagement" },
  { value: "Global Business Management", label: "Global Business Management" },
  {
    value: "Cross-functional Team Leadership",
    label: "Cross-functional Team Leadership",
  },
  { value: "Mergers and Acquisitions", label: "Mergers and Acquisitions" },
  {
    value: "Data-Driven Decision Making",
    label: "Data-Driven Decision Making",
  },
  { value: "Ethical Leadership", label: "Ethical Leadership" },
  {
    value: "Strategic Business Planning",
    label: "Strategic Business Planning",
  },
  { value: "Agile Leadership", label: "Agile Leadership" },
  {
    value: "Digital Transformation Strategy",
    label: "Digital Transformation Strategy",
  },
  { value: "Financial Acumen", label: "Financial Acumen" },
  { value: "Change Management", label: "Change Management" },
  { value: "AI & Automation Strategy", label: "AI & Automation Strategy" },
  { value: "Information Architecture", label: "Information Architecture" },
  { value: "UX Testing", label: "UX Testing" },
  {
    value: "Virtual Reality (VR) Design",
    label: "Virtual Reality (VR) Design",
  },
  {
    value: "Influencer Marketing Strategy",
    label: "Influencer Marketing Strategy",
  },
  { value: "User Journey Mapping", label: "User Journey Mapping" },
  { value: "User Onboarding Design", label: "User Onboarding Design" },
  { value: "UX Writing", label: "UX Writing" },
  { value: "Iterative Prototyping", label: "Iterative Prototyping" },
  { value: "Product Roadmapping", label: "Product Roadmapping" },
  {
    value: "Augmented Reality (AR) Design",
    label: "Augmented Reality (AR) Design",
  },
  { value: "DeFi Governance", label: "DeFi Governance" },
  { value: "Smart Contract Auditing", label: "Smart Contract Auditing" },
  { value: "Framer", label: "Framer" },
  { value: "NFT Marketing", label: "NFT Marketing" },
  { value: "DAO Governance", label: "DAO Governance" },
  {
    value: "Hybrid-remote Team Management",
    label: "Hybrid-remote Team Management",
  },
  {
    value: "Verifiable Credentials",
    label: "Verifiable Credentials",
  },
  { value: "Quantum Computing", label: "Quantum Computing" },
  { value: "Surveillance AI Ethics", label: "Surveillance AI Ethics" },
  { value: "Proactive AI Ethics", label: "Proactive AI Ethics" },
  { value: "Conversational Design", label: "Conversational Design" },
  {
    value: "AI Bias Detection",
    label: "AI Bias Detection",
  },
  { value: "Cybersecurity", label: "Cybersecurity" },
  {
    value: "Interoperable Blockchains",
    label: "Interoperable Blockchains",
  },
  {
    value: "DAO Architecture",
    label: "DAO Architecture",
  },
  { value: "AI Ethics", label: "AI Ethics" },
  {
    value: "Mechatronics",
    label: "Mechatronics",
  },
  { value: "Metaverse Product Design", label: "Metaverse Product Design" },
  { value: "Web3 UX Design", label: "Web3 UX Design" },
]
